# GPU Deploy
# Used to give the container access to GPUs on the device.
services:
  isaac-lab:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
